# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62602903018ed99581dc132f6eb2211a0ed28e169b8f1facbec54baed3cb13780c6052f0160f5fa3c544d3dca7533cf4189d58a891a07b2eda01a7f45eadb1f9

test:
  secret_key_base: c9e474b45e2bab69189d8c35bc37e81a1e176b9d341ec2974dee6d1eaf0aab2d7789615a8efc8894531a03a98c76e31a6367ed5b1b31793ee5cc0d5f708a492c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
